# Generated by Django 5.2.2 on 2025-06-07 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('time_zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_zone_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('date_time', models.BigIntegerField()),
                ('no_of_slots', models.PositiveIntegerField()),
                ('time_zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.timezone')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.class')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.user')),
            ],
        ),
    ]
